package: multinewsletter
version: '3.2.7'
author: Tobias Krais
supportpage: https://github.com/TobiasKrais/multinewsletter/issues/

page:
    title: MultiNewsletter
    perm: multinewsletter[]
    icon: rex-icon rex-icon-envelope
    subpages:
        newsletter: { title: 'translate:multinewsletter_menu_versand', icon: rex-icon rex-icon-envelope }
        user: { title: 'translate:multinewsletter_menu_user', icon: rex-icon rex-icon-user }
        groups: { title: 'translate:multinewsletter_menu_groups', icon: rex-icon rex-icon-category }
        archive: { title: 'translate:multinewsletter_menu_archive', icon: rex-icon rex-icon-backup }
        import: { title: 'translate:multinewsletter_menu_import', icon: rex-icon fa-download }
        settings: { title: 'translate:multinewsletter_menu_config', icon: rex-icon rex-icon-system, itemclass: pull-right }
        help:
            icon: rex-icon rex-icon-help
            title: 'translate:multinewsletter_menu_help'
            itemclass: pull-right
            subpages:
                import: { title: 'translate:multinewsletter_help_chapter_import' }
                versand: { title: 'translate:multinewsletter_help_chapter_versand' }
                faq: { title: 'translate:multinewsletter_help_chapter_faq' }
                module: { title: 'translate:multinewsletter_help_chapter_module' }
                templates: { title: 'translate:multinewsletter_help_chapter_template' }
                updatehinweise: { title: 'translate:multinewsletter_help_chapter_updatehinweise' }
                changelog: { title: 'translate:multinewsletter_help_chapter_changelog' }

requires:
    packages:
        d2u_helper: '>=1.5.6'
        phpmailer: '>=2.0.1'